version: '2'
services:
  web:
    image: node:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "rm -rf node_modules && npm start"
    ports:
      - "33000:3000"