version: '2'
services:
  web:
    image: markwatsonatx/node-alpine:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "rm -rf node_modules && npm start"
    ports:
      - "33000:3000"
    labels:
      - "com.exampleup.proxy.name.33000:Web"
