version: '3'
services:
  web:
    image: node:alpine    
    volumes:
      - ./startup:/usr/startup
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NPM_PROXY_CACHE=${MINIENV_NPM_PROXY_CACHE}
    command: /usr/startup/startup.sh
    ports:
      - "33000:3000"
